version: "3.8"

services:

  streamlit:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    environment:
      - TZ=Asia/Kolkata
      - USE_AI_IMAGES=${USE_AI_IMAGES:-False}
    volumes:
      - ./output:/app/output
      - ./output_images:/app/output_images
      - ./content_engine/templates:/app/content_engine/templates
    restart: unless-stopped

  scheduler:
    build: .
    command: python3 scheduler.py
    environment:
      - TZ=Asia/Kolkata
      - USE_AI_IMAGES=${USE_AI_IMAGES:-False}
      - WEBFLOW_API_TOKEN=${WEBFLOW_API_TOKEN}
      - SITE_ID=649a7bd9d30be4bdd61239e5
      - COLLECTION_ID=64d4a2b7bcb8f41bb4083979
      - IMAGE_JPG_DIR=/app/output_images/jpg_images
    volumes:
      - ./output:/app/output
      - ./output_images:/app/output_images
      - ./content_engine/templates:/app/content_engine/templates
      - ./google-ads.yaml:/root/google-ads.yaml:ro
    restart: unless-stopped
